stable_ssl/data/augmentations.py, stable_ssl/data/base.py
=> [BugFix] CPU Count Slurm (#24), Augmentations bugfix (#25)

.gitignore, examples/configs/simclr_cifar10.yaml, examples/configs/supervised_cifar10.yaml, examples/configs/supervised_cifar10_multigpu.yaml, stable_ssl/base.py, stable_ssl/config.py, stable_ssl/data/base.py, stable_ssl/utils/utils.py
+ cleanup should be done even with world_size 1 as we create distributed group even then.
=> [BugFix] CPU workers should be per task not job. GPUs should be per job not per task. Logging for DDP.

stable_ssl/base.py, stable_ssl/config.py, stable_ssl/joint_embedding/base.py, stable_ssl/supervised.py
=> [Clean] unify logging function names

stable_ssl/supervised.py
=> [Feature] flexible supervised learning with any number of views

stable_ssl/base.py, stable_ssl/data/base.py, stable_ssl/utils/utils.py
1. GPU and CUDA OOM resolution.
2. Epoch to be added as a key in eval logging.
=>  Cleanup GPU Device at process start, at termination and at preemption due to timeout. Log epoch in eval.

stable_ssl/base.py
move the temporary checkpoint in the checkpoint method called when job is being preempted. And adding a checkpoint with epoch number as needed by the user
=> checkpointing-defaults

benchmarks/config/simclr/cifar10.yaml, benchmarks/run.py, stable_ssl/base.py, stable_ssl/config.py
=> [Feature] config objects to specify default parameters for logging and wandb

stable_ssl/trainers.py
=> [Minor] Notations embeddings -> representations, projections -> embeddings

stable_ssl/base.py
=> wandbrun + error management

stable_ssl/base.py
=> handling of breakallepochs

stable_ssl/base.py
=> moved wandb cleanup

stable_ssl/base.py
=> clean utility

stable_ssl/base.py
=> remove hardcoded .item()

.github/workflows/testing.yml, benchmarks/cifar10/barlowtwins.yaml, benchmarks/cifar10/byol.yaml, benchmarks/cifar10/simclr.yaml, benchmarks/cifar10/vicreg.yaml, benchmarks/cifar100/shared_config.yaml
=> [Feature] setup codecov

benchmarks/cifar10/barlowtwins.yaml, benchmarks/cifar10/dino.yaml, benchmarks/cifar10/vicreg.yaml, benchmarks/cifar100/dino.yaml, benchmarks/cifar100/vicreg.yaml, benchmarks/imagenette/barlowtwins.yaml, benchmarks/imagenette/dino.yaml, stable_ssl/modules.py, stable_ssl/tests/configs/mini_mnist.yaml, stable_ssl/tests/configs/mnist.yaml, stable_ssl/tests/test_cli.py
=> [Test] CLI test with MNIST

stable_ssl/reader.py
=> wandb reader + formatter

stable_ssl/base.py
=> [BUGFIX] lazy + wandb sweeps

pyproject.toml, stable_ssl/base.py
=> [BUGFIX] wandb config update

stable_ssl/base.py, stable_ssl/utils/__init__.py, stable_ssl/utils/utils.py
=> [BugFix] rgetattr-rsetattr in utils

stable_ssl/data.py, stable_ssl/reader.py, stable_ssl/tests/configs/tiny_mnist.yaml, stable_ssl/tests/local_test.py, stable_ssl/tests/test_base.py, stable_ssl/tests/test_data.py
=> HF dataset + wandb

README.md, TESTING.md, pytest.ini, stable_ssl/backbone/utils.py, stable_ssl/callbacks/queue.py, stable_ssl/tests/README.md, stable_ssl/tests/scripts/train_simclr_cifar10.py
=> [BugFix] store queues in _callbacks_modules for consistency

stable_ssl/__init__.py, stable_ssl/callbacks/knn.py, stable_ssl/callbacks/probe.py, stable_ssl/callbacks/queue.py, stable_ssl/tests/integration/test_probing.py, stable_ssl/tests/scripts/train_simclr_cifar10_multigpu.py, stable_ssl/tests/unit/test_probing.py, stable_ssl/utils/__init__.py, stable_ssl/utils/batch_utils.py, stable_ssl/utils/nn_modules.py
=> [Feature] Allow to get data from batch or outputs for better compatibility with Lightning

benchmarks/cifar10/byol-resnet18.py, benchmarks/cifar10/simclr-resnet18.py, docs/source/api/backbone.rst, docs/source/api/gen_modules/stable_ssl.backbone.TeacherStudentModule.rst, stable_ssl/__init__.py, stable_ssl/backbone/__init__.py, stable_ssl/backbone/utils.py, stable_ssl/callbacks/__init__.py, stable_ssl/callbacks/teacher_student.py, stable_ssl/data/__init__.py, stable_ssl/data/transforms.py, stable_ssl/data/utils.py, stable_ssl/losses.py, stable_ssl/manager.py, stable_ssl/module.py, stable_ssl/optim/__init__.py, stable_ssl/optim/lr_scheduler.py
=> [Feature] Teacher/Student wrapper + callback & BYOL benchmark

benchmarks/cifar10/byol-resnet18.py, benchmarks/cifar10/simclr-resnet18.py, pyproject.toml, stable_ssl/callbacks/checkpoint_sklearn.py, stable_ssl/callbacks/factories.py, stable_ssl/callbacks/image_retrieval.py, stable_ssl/callbacks/knn.py, stable_ssl/callbacks/lidar.py, stable_ssl/callbacks/probe.py, stable_ssl/callbacks/queue.py, stable_ssl/callbacks/rankme.py, stable_ssl/callbacks/trainer_info.py, stable_ssl/callbacks/utils.py, stable_ssl/callbacks/writer.py, stable_ssl/manager.py, stable_ssl/tests/unit/test_probing.py
=> [Bugfix] callback factories

examples/simclr_cifar10_config.yaml, pyproject.toml, stable_pretraining/cli.py, stable_pretraining/run.py
=> [Feature] spt CLI command

stable_pretraining/callbacks/__init__.py, stable_pretraining/callbacks/embedding_cache.py, stable_pretraining/tests/scripts/train_supervised_multigpu_requeue.py
=> [Feature] Embedding cache Callback

stable_pretraining/callbacks/__init__.py, stable_pretraining/callbacks/earlystop.py
=> EpochMilestones

benchmarks/cifar10/barlow-resnet18.py, benchmarks/cifar10/byol-resnet18.py, benchmarks/cifar10/byol-resnet50.py, benchmarks/cifar10/simclr-resnet18.py, benchmarks/cifar10/vicreg-resnet18.py, benchmarks/imagenet100/byol-resnet50-8gpus.py, benchmarks/imagenet100/vicreg-resnet50.py, stable_pretraining/callbacks/factories.py, stable_pretraining/callbacks/teacher_student.py, stable_pretraining/forward.py, stable_pretraining/manager.py
=> [BugFix] BYOL teacher-student callback automatic trigger

stable_pretraining/backbone/utils.py
=> [BugFix] ema coefficient as buffer

benchmarks/imagenet100/vicreg-resnet50.py, stable_pretraining/data/transforms.py, stable_pretraining/forward.py
=> [Feature] dict structure for MultiViewTransform

stable_pretraining/callbacks/__init__.py, stable_pretraining/callbacks/wd_schedule.py
=> [Feature] weight decay scheduler callback

benchmarks/data_loader/README.md, benchmarks/data_loader/benchmark_data_loading.py
=> [Benchmark] data loader : multiview vs roundrobin 

stable_pretraining/backbone/utils.py, stable_pretraining/data/transforms.py
=> [BugFix] Teacher Student and ReturnFeatures

benchmarks/imagenet100/dino-vit-tiny.py, benchmarks/imagenet100/dinov2-vit-tiny-8gpus.py, benchmarks/imagenet100/dinov2-vit-tiny.py, stable_pretraining/backbone/__init__.py, stable_pretraining/backbone/utils.py, stable_pretraining/forward.py, stable_pretraining/losses/__init__.py, stable_pretraining/losses/dino.py, stable_pretraining/module.py, stable_pretraining/optim/lr_scheduler.py, stable_pretraining/optim/utils.py, stable_pretraining/tests/unit/test_ibot_patch_loss.py
=> [Feature] DINOv2

stable_pretraining/tests/unit/test_nn_modules.py, stable_pretraining/utils/nn_modules.py
Queue-based callbacks (UnsortedQueue and OrderedQueue) previously crashed when receiving batches larger than the queue capacity. This is a valid use case for monitoring metrics over smaller temporal windows than the batch size.
Changes:
- Modified UnsortedQueue.append() to handle batch_size >= max_length
- Modified OrderedQueue.append() to handle batch_size >= max_length
- When batch exceeds queue size, keep only the last max_length items
- Added comprehensive tests for both queue types with large batches
Fixes issue where delta-hyperbolicity callbacks with small queue_length (e.g., 32, 64, 128) would fail with SimCLR batch_size=256 (512 embeddings).
=> [BugFix] Fix queue callbacks to handle batch size larger than queue length

stable_pretraining/backbone/__init__.py, stable_pretraining/backbone/probe.py, stable_pretraining/callbacks/__init__.py, stable_pretraining/callbacks/cleanup.py, stable_pretraining/callbacks/image_retrieval.py, stable_pretraining/callbacks/trainer_info.py, stable_pretraining/module.py, stable_pretraining/tests/unit/test_clip_zero_shot.py
=> [Feature] cleanup callback + probes
